# Generated by Django 4.2.4 on 2023-08-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingProgram', '0001_initial'),
        ('profiles', '0004_client_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_share_percentage', models.IntegerField()),
                ('stripe_subscription_id', models.CharField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.client')),
                ('training_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingProgram.trainingprogram')),
            ],
        ),
    ]
