# Generated by Django 4.2.4 on 2023-09-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_client_payment_method'),
        ('subscription', '0004_alter_paymentmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.client'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('client', 'number')},
        ),
    ]
