# Generated by Django 4.2.4 on 2023-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_paymentmethod_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
