# Generated by Django 4.2.4 on 2023-10-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_client_default_card'),
        ('subscription', '0006_paymentmethod_stripe_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='profiles.client'),
        ),
    ]
