# Generated by Django 4.2.4 on 2023-10-10 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscribe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='current_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
