# Generated by Django 4.2.4 on 2023-08-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_sportcategory_coach_biography_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='sport_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.sportcategory'),
        ),
    ]
