# Generated by Django 4.2.4 on 2023-10-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_paymentmethod_stripe_payment_method_id'),
        ('profiles', '0006_remove_client_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_default_payment_method', to='subscription.paymentmethod', verbose_name='Default card'),
        ),
    ]
