# Generated by Django 4.2.4 on 2023-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingProgram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='price_id_stripe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
