# Generated by Django 4.2.4 on 2023-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingProgram', '0002_trainingprogram_price_id_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='coach_share_percentage',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
