# Generated by Django 4.2.4 on 2023-10-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingProgram', '0003_trainingprogram_coach_share_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='product_id_stripe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
